### ISSUE TITLE
Permission & chat bug

### ISSUE THREAD

**Issue by whity78** [montlikadani/BannedWordsPlus#1]
[17:23:05] [Server thread/ERROR]: Could not pass event PlayerChatEvent to BannedWordsPlus v1.7
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at net.minecraft.server.v1_12_R1.PlayerConnection$7.evaluate(PlayerConnection.java:1328) [spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:758) [spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_151]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_151]
	at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:168) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:149) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.craftbukkit.v1_12_R1.command.ServerCommandSender.recalculatePermissions(ServerCommandSender.java:66) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.plugin.SimplePluginManager.dirtyPermissibles(SimplePluginManager.java:655) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.plugin.SimplePluginManager.calculatePermissionDefault(SimplePluginManager.java:634) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.plugin.SimplePluginManager.recalculatePermissionDefaults(SimplePluginManager.java:626) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.permissions.Permission.recalculatePermissibles(Permission.java:165) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.permissions.Permission.<init>(Permission.java:67) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.permissions.Permission.<init>(Permission.java:27) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at hu.montlikadani.BannedWords.Permissions.<init>(Permissions.java:23) ~[?:?]
	at hu.montlikadani.BannedWords.Listeners.onPlayerChat(Listeners.java:202) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor363.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	... 10 more

**Comment by montlikadani** [comment]
@whity78 
What did you write or did before this error came up?

**Comment by whity78** [comment]
Here are some parts of the log.

[17:51:13] [Thread-32/INFO]: [[0;37;1mOpenworld[0;37;1m] [0;37;22m[Spieler][0;37;1m FabiMaldini: Alles klar :) bin jetzt auch raus :)[m
[17:51:20] [Async Chat Thread - #34/ERROR]: Could not pass event AsyncPlayerChatEvent to BannedWordsPlus v1.7
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]

-----------------------------------------------------------------------------------------------------------
[17:50:33] [Thread-32/INFO]: [[0;37;1mOpenworld[0;37;1m] [0;37;22m[Spieler][0;37;1m Adiman17: ne burg, etc, etc etc[m
[17:50:56] [Async Chat Thread - #33/ERROR]: Could not pass event AsyncPlayerChatEvent to BannedWordsPlus v1.7
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4bd94dc-bdcc7c7]

-----------------------------------------------------------------------------------------------------------
[17:46:27] [Thread-32/INFO]: [[0;37;1mOpenworld[0;37;1m] [0;37;22m[Spieler][0;37;1m FabiMaldini: Bisher halt nur gefarmt und was verzaubert :)[m
[17:46:40] [Async Chat Thread - #32/ERROR]: Could not pass event AsyncPlayerChatEvent to BannedWordsPlus v1.7
org.bukkit.event.EventException: null

**Comment by montlikadani** [comment]
@whity78 
Please send a full server log.txt.

**Comment by montlikadani** [comment]
**This long error will only appear if a sudden server laggs.**

**Comment by montlikadani** [comment]
**This bug is resolved and the plugin is updated:** https://www.spigotmc.org/resources/bannedwordsplus.42983/update?update=213949
